runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /static
  static_dir: static

- url: /.*
  script: ghostgame.app
  login: optional

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(archive/)+.*$
- ^(.*/)?.*\.md$
- ^(requirements)\.txt$
- ^(note)\.txt$